#!/bin/python3
from os import geteuid as usertype
from os import popen
from sys import exit
import click

# ============ Functions

def nudo(command):
    """
    This performs a command as a normal user and
    returns the output as a string.
    
    :param command: valid bash command
    :return: string output
    """
    pipe = popen(f'{command}')
    output = pipe.read()
    pipe.close()
    return output[:-1]  # Return everying except the last char


# ============ Main Function
@click.command()
@click.option('-c', '--change', 'change', default=-20 , help='This specifies the brightness change')
def start(change):
    # 1. Get info
    # The below use of sudo -u allows me to decrease privs temporarily
    bright = nudo(f'pkexec mate-power-backlight-helper --get-brightness')

    try:
        bright = int(bright)
    except Exception as e:
        print(f'Error: {str(e)}')
        exit(1)

    # 2. Act on info

    # 2.1 Figure out how much to change 
    if 'int' in str(type(change)):
        changeby = change / 100
    elif 'float' in str(type(change)):
        changeby = change  # Make no changes
    else:
        changeby = change / 100
        print(f'ERROR: TYPE = {str(type(change))}')

    # 2.2 Determine if change is viable
    diff = int(bright + (bright * changeby))

    
    if diff > 120000:  # If the total change is more than max
        new_bright = 120000  # Set brightness to max
    elif diff < 1000:  # If change makes it effectively off
        new_bright = 1000  # Minimize brightness, but dont turn off (still visible)
    else:  # Otherwise, if it's not a total change
        new_bright = diff  # Just implement it
        
    # 3. Apply change
    nudo(f'pkexec mate-power-backlight-helper --set-brightness {new_bright}')
    exit(0)

# ============ START
if __name__ == '__main__':
    start()
