#!/bin/bash
redshift -O 4900 > /dev/null 2>&1
redshift -O 4900 > /dev/null 2>&1
redshift -O 4900 > /dev/null 2>&1
redshift -O 4900 > /dev/null 2>&1
redshift -O 4900 > /dev/null 2>&1
redshift -O 4900 > /dev/null 2>&1
redshift -O 4900 > /dev/null 2>&1
redshift -O 4900 > /dev/null 2>&1
dark -c-50

